# Generated by Django 4.2.1 on 2023-07-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
    ]
