# Generated by Django 4.2.1 on 2023-07-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
