# Generated by Django 4.2.1 on 2023-07-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_details_name_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='bonus',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='present',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='leave',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
