# Generated by Django 4.2.1 on 2023-07-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_details_bonus_details_present_alter_details_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('Aadhar_no', models.CharField(max_length=20)),
                ('PAN', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=20)),
                ('diploma', models.CharField(max_length=20)),
                ('class10', models.CharField(max_length=20)),
                ('class12', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
