# Generated by Django 4.2.1 on 2023-07-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', unique=True),
        ),
    ]
