# Generated by Django 4.2.1 on 2023-07-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_background_name_alter_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='skills',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Emp_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance', models.CharField(max_length=20)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
