# Generated by Django 4.2.1 on 2023-07-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_background_skills_emp_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_salary',
            name='Attendance',
        ),
        migrations.AddField(
            model_name='emp_salary',
            name='halfday',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='emp_salary',
            name='latecoming',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='emp_salary',
            name='leave',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='emp_salary',
            name='month',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='emp_salary',
            name='present',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='emp_salary',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', unique=True),
        ),
        migrations.AddField(
            model_name='emp_salary',
            name='attendance',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
