# Generated by Django 4.2.1 on 2023-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_emp_salary_attendance_emp_salary_halfday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, null='false')),
                ('technology', models.CharField(max_length=100)),
                ('add_employee', models.JSONField(max_length=100)),
            ],
        ),
    ]
