# Generated by Django 4.2.1 on 2023-07-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='add_employee',
            field=models.CharField(max_length=100),
        ),
    ]
