# Generated by Django 4.2.1 on 2023-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_remove_project_add_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
