# Generated by Django 4.2.1 on 2023-08-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
