# Generated by Django 4.2.1 on 2023-08-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
